import type { Metadata } from "next";
import {
  Baloo_2,
  Inter,
  Lobster,
  Montserrat,
  Noto_Sans,
  Oxygen,
  Pacifico,
  Poppins,
  Quicksand,
  Raleway,
  Roboto,
  Unbounded,
} from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import { Special_Elite, Orbitron, Share_Tech_Mono } from "next/font/google";
import Footer from "./components/Footer";
import Providers from "./Providers";
// Specify the font weights and styles you want to use
const roboto = Special_Elite({
  subsets: ["latin"], // Specify subsets (e.g., 'latin', 'latin-ext')
  weight: "400", // Specify the font weight (e.g., '400', '700')
  style: "normal", // Specify the font style (e.g., 'normal', 'italic')
});
const orbitron = Orbitron({
  subsets: ["latin"], // Specify subsets (e.g., 'latin', 'latin-ext')
  weight: "400", // Specify the font weight (e.g., '400', '700')
  style: "normal", // Specify the font style (e.g., 'normal', 'italic')
});
const share = Share_Tech_Mono({
  subsets: ["latin"], // Specify subsets (e.g., 'latin', 'latin-ext')
  weight: "400", // Specify the font weight (e.g., '400', '700')
  style: "normal", // Specify the font style (e.g., 'normal', 'italic')
});
const inter = Inter({ subsets: ["latin"] });

const unbounded = Montserrat({
  subsets: ["latin"],
  weight: "400",
  style: "normal",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" id="root">
      <body className={(inter.className, unbounded.className)}>
        <Providers>
          <Navbar />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
